# $OpenBSD$

COMMENT =	Python wrapper for HTML Tidy (tidylib)

MODPY_EGG_VERSION =	0.3.2

DISTNAME =	pytidylib-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	www

HOMEPAGE =	http://countergram.com/open-source/pytidylib/

# MIT
PERMIT_PACKAGE =	Yes

FLAVOR =		python3
FLAVORS =		python3

MODULES =		lang/python
MODPY_PI =		Yes
MODPY_PYTEST =		Yes

.include <bsd.port.mk>
