# $OpenBSD$

COMMENT =	textbox edit widget for urwid that supports readline

MODPY_EGG_VERSION =	0.13

DISTNAME =	urwid_readline-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	devel

HOMEPAGE =	https://github.com/rr-/urwid_readline

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
FLAVOR =		python3
FLAVORS =		python3

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
